apiVersion: v1
kind: Service
metadata:
  name: msk-external
  namespace: kafka
spec:
  type: ExternalName
  externalName: b-1.example-msk.xxxxxxx.kafka.us-east-1.amazonaws.com
  ports:
    - name: kafka-9092
      port: 9092
      targetPort: 9092
      protocol: TCP
    - name: kafka-9094
      port: 9094
      targetPort: 9094
      protocol: TCP
